; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rpipico

[env:rpipico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5

[env:waveshare_rp2040_zero]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = waveshare_rp2040_zero
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel@^1.12.5

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
board_fuses.lfuse = 0xEE
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFD
build_flags = -D ATmega328_168

[env:micro]
platform = atmelavr
board = micro
board_fuses.lfuse = 0xEE
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFD
build_flags = -D ATmega32U4_16U4

[env:attiny85]
platform = atmelavr
board = attiny85
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFD
build_flags = -D ATtiny85_45_25

[env:attiny45]
platform = atmelavr
board = attiny45
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFD
build_flags = -D ATtiny85_45_25

[env:attiny25]
platform = atmelavr
board = attiny25
board_fuses.lfuse = 0xE2
board_fuses.hfuse = 0xDF
board_fuses.efuse = 0xFD
build_flags = -D ATtiny85_45_25
